---
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
  sudo: yes

- name: install gdebi
  apt: name=gdebi
  sudo: yes

- name: Check if slack is installed
  command: dpkg-query -W slack-desktop
  register: check_slack
  failed_when: false
  changed_when: false

- name: Download Ubuntu slack package
  command: "wget -O /tmp/slack-desktop.deb https://downloads.slack-edge.com/linux_releases/slack-desktop-{{ slack_version }}-amd64.deb"
  args:
    creates: "/tmp/slack-desktop.deb"
  when: check_slack.rc == 1

- name: Install Ubuntu slack package
  sudo: true
  command: gdebi --non-interactive /tmp/slack-desktop.deb
  when: check_slack.rc == 1
